; Generated by AutoGUI 2.6.2
#SingleInstance Force
#NoEnv
;#NoTrayIcon
#Include, function.ahk
;#Include sogou.ahk
;


#z::  ; Win+Z 热键
AutoTrim Off  ; 保留剪贴板中任何前导和尾随空白字符.
ClipboardOld := ClipboardAll
Clipboard := ""  ; 必须清空, 才能检测是否有效.
Send ^c
ClipWait 1
;if ErrorLevel  ; ClipWait 超时.
;    return

SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 321

Gui Main1: New, +LabelMain +hWndhMainWnd +Resize -MinimizeBox
Menu ContextMenu, Add, &Open...`tCtrl+O, import
Menu ContextMenu, Icon, &Open...`tCtrl+O, shell32.dll, 4

Gui Add, Text, x10 y10 w350 h25, %abbreL%
Gui Add, Edit, hWndhEdtValue vabbre x10 y35 w250 h25
Gui Add, Text, hWndhTxtText2 vTxtText1 x10 y65 w80 h25, %folderL%
Gui Add, Edit, hWndhEdtValue vfather x80 y65 w120 h25, self
Gui Add, Text, hWndhTxtText2 vTxtText2 x10 y100 w80 h25, %descriptionL%
Gui Add, Edit, hWndhEdtValue vdescription x80 y100 w120 h25
Gui Add, Text, hWndhTxtText2 vTxtText4 x10 y130 w120 h25, %shortCutL%
Gui Add, DropDownList, x80 y130 w120, ]||
Gui Add, Text, hWndhTxtText3 vTxtText3 x10 y155 w250 h25, %supportL%
Gui Add, Edit, vvalue x10 y180 w600 h200,%Clipboard%
Gui Add, Button, gaddPhraseHandle1 x440 y390 w80 h25, %addL%
Gui Add, Button, x530 y390 w80 h25 gcancel1, %cancelL%


Menu sogou, Add, Sogou, MenuHandler
Menu FileMenu, Add, import, :sogou
Menu MenuBar, Add, &File, :FileMenu


Menu help, Add, document, HelpMenuHandler
Menu MenuBar, Add, &Help, :help

Gui Menu, MenuBar

Gui Show, w620 h420, %addPhraseL%
Return

import:
Return

MenuHandler:
    importSogo()
Return

HelpMenuHandler:
	Run https://gitee.com/smartString/smart_string
Return

addPhraseHandle1(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
    GuiControlGet abbre
    GuiControlGet value
    GuiControlGet father
    GuiControlGet description
    result := add(abbre,value,father,description)
    if(result == 0){
        reload
        Sleep 200 ; 如果加载成功, reload 会在 Sleep 期间关闭当前实例, 所以永远不会执行到下面的语句.
        MsgBox, 4,, The hotstring just added appears to be improperly formatted. Would you like to open the script for editing? Note that the bad hotstring is at the bottom of the script.
        IfMsgBox, Yes, Edit
        return

        MoveCaret:
        IfWinNotActive, New Hotstring
            return
        ; 否则移动 InputBox 中的光标到用户输入缩写的位置.
        Send {Home}{Right 3}
        SetTimer, MoveCaret, Off
        return
    }  
}


cancel1(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") { 
    Gui hide
}

Main1Size:
    If (A_EventInfo == 1) {
        Return
    }
Return

Main1ContextMenu:
    Menu ContextMenu, Show
Return

Main1Escape:
Main1Close:
    Gui hide
    ;ExitApp
#Include send.ahk